---
- name: Set up os packages
  ansible.builtin.import_tasks: setup/os_packages.yml
  tags: setup_os_packages

- name: Set up os users
  ansible.builtin.import_tasks: setup/os_users.yml
  tags: setup_os_users
