---
- name: Test os packages
  ansible.builtin.import_tasks: test/os_packages.yml
  tags: test_os_packages

- name: Test os users
  ansible.builtin.import_tasks: test/os_users.yml
  tags: test_common
