name: ansible-lint
on:
  - push
  - pull_request

jobs:
  lint:
    name: Ansible lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@main
        with:
          path: playbooks/
